global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape the dedicated metrics endpoint
  - job_name: "predictive-dash-app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["predictive-dash-app:3000"]
